// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "AutonDrive.h"
#include "C:/Windriver/workspace/frc1388-2014/Robot2014/Subsystems/DriveTrain.h"
AutonDrive::AutonDrive(float setpoint, float maxPower = 1) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_setpoint = setpoint;
	m_maxPower = maxPower;
}
// Called just before this Command runs the first time
void AutonDrive::Initialize() {
	RobotMap::driveTrainLeftEncoder->Reset();
	RobotMap::driveTrainRightEncoder->Reset();
}
// Called repeatedly when this Command is scheduled to run
void AutonDrive::Execute() {
	
	
	float leftPosition = RobotMap::driveTrainLeftEncoder->GetDistance();
	float rightPosition = RobotMap::driveTrainRightEncoder->GetDistance();
	float leftPower = (m_setpoint - leftPosition) * 0.6;
	float rightPower = (m_setpoint - rightPosition) * 0.6;
	//limit to max power passed into the constructor
	leftPower = (leftPower > m_maxPower) ? m_maxPower : leftPower;
	rightPower = (rightPower > m_maxPower) ? m_maxPower : rightPower;
	RobotMap::driveTrainMyRobotDrive->TankDrive(leftPower, rightPower, false);
}
// Make this return true when this Command no longer needs to run execute()
																
bool AutonDrive::IsFinished() {
	float leftPosition = RobotMap::driveTrainLeftEncoder->GetDistance();
	float rightPosition = RobotMap::driveTrainRightEncoder->GetDistance();
	
	
	if(leftPosition == m_setpoint && rightPosition == m_setpoint)
	{
		return true;
	}else{
		return false;
	}
}
// Called once after isFinished returns true
void AutonDrive::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonDrive::Interrupted() {
}
