// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "AutonomousGroup.h"
#include "GoToShoot.h"
#include "DriveForward.h"
#include "Shoot.h"
#include "CockShooterGroup.h"
AutonomousGroup::AutonomousGroup() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.
	//We found out that you must add the parameters to get the sequential to work
	//TODO: we need to verify the shooting sequence
	//TODO: need to find out the time parameters for the wait and drive forward commands
	//TODO: find out how long it takes to get the claw to the zero position
	AddParallel(new CockShooterGroup());
	AddSequential(new GoToShoot());
	AddSequential(new DriveForward(1,1));
	AddSequential(new WaitCommand(1));
	AddSequential(new Shoot());
	

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.
}
