// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "CockShooter.h"
#define COCKING_SPEED -0.7
#define HOLD_SPEED 0.2
#define BACK_OFF 0.4
CockShooter::CockShooter() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void CockShooter::Initialize() {
	Robot::shooter->loadingMotor->Set(COCKING_SPEED);
}
// Called repeatedly when this Command is scheduled to run
void CockShooter::Execute() {
	bool isCocked = Robot::shooter->cockedLimitSwitch->Get();
	bool tooFar = Robot::shooter->tooFarLimitSwitch->Get();
	
	if(isCocked == true)
	{
		Robot::shooter->loadingMotor->Set(HOLD_SPEED);
	}
	
	if(tooFar == true)
	{
		Robot::shooter->loadingMotor->Set(BACK_OFF);
	}
	
}
// Make this return true when this Command no longer needs to run execute()
bool CockShooter::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void CockShooter::End() {
	Robot::shooter->loadingMotor->Set(HOLD_SPEED);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void CockShooter::Interrupted() {
	End();
}
