// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "SetPosition.h"



SetPosition::SetPosition(int setPosition) {
	
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::claw);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	
	SetPosition::position = setPosition;
	
}

// Called just before this Command runs the first time
void SetPosition::Initialize() {
	Robot::claw->SetSetpoint(SetPosition::position);
	
	
}

// Called repeatedly when this Command is scheduled to run
void SetPosition::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool SetPosition::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void SetPosition::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetPosition::Interrupted() {

}
