// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "SpeedDrive.h"
#include "Math.h"
SpeedDrive::SpeedDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void SpeedDrive::Initialize()
{
	
}
// Called repeatedly when this Command is scheduled to run
void SpeedDrive::Execute()
{
	float leftStick = Robot::oi->getLeftYAxis();
	float rightStick = -(Robot::oi->getRightYAxis());
	
	float rawLeftRate = (float) Robot::driveTrain->leftEncoder->GetRate();
	float rawRightRate = (float) Robot::driveTrain->rightEncoder->GetRate();
	
	printf("Raw Left Rate: %f, Raw Right Rate: %f \r\n", rawLeftRate, rawRightRate);
	
	// 16 represents the counts for full speed
	float scaledLeftRate = (rawLeftRate / 16.0);
	float scaledRightRate = (rawRightRate / 16.0);
	
	// 0.0280499 is the feet per counts on Pheonix
	
	float leftError = leftStick - (scaledLeftRate * Robot::SignOf(leftStick));
	
	// limits the range of the leftError	
	if(leftError > 0.5)
	{
		leftError = 0.5;
	}
	else if(leftError < -0.5)
	{
		leftError = -0.5;
	}
	
	float rightError = rightStick - (scaledRightRate * Robot::SignOf(rightStick));
	
	// limits the range of rightError
	if(rightError > 0.5)
	{
		rightError = 0.5;
	}
	else if(rightError < -0.5)
	{
		rightError = -0.5;
	}
	
	Robot::driveTrain->myRobotDrive->TankDrive(leftError, rightError, false);
	
//	Robot::driveTrain->leftMotor->Set(leftError);
//	Robot::driveTrain->rightMotor->Set(rightError);
	
	printf("Left Motor Power: %f, Right Motor Power: %f \r\n", Robot::driveTrain->leftMotor->Get(),
			Robot::driveTrain->rightMotor->Get());
	
//	if(fabs(leftStick) < 0.05 || fabs(rightStick) < 0.05)
//	{
//		Robot::driveTrain->leftEncoder->Reset();
//		Robot::driveTrain->rightEncoder->Reset();
//	}
}
// Make this return true when this Command no longer needs to run execute()
bool SpeedDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void SpeedDrive::End()
{
	Robot::driveTrain->myRobotDrive->TankDrive(0.0, 0.0, false);
	
//	Robot::driveTrain->leftMotor->Set(0);
//	Robot::driveTrain->rightMotor->Set(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SpeedDrive::Interrupted()
{
	End();
}
