// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TriggerCommand.h"
#include "Shoot.h"
#include "ShootAndCock.h"
TriggerCommand::TriggerCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void TriggerCommand::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void TriggerCommand::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool TriggerCommand::IsFinished() {
	if(Robot::oi->getLeftDriverStick()->GetTrigger() == true &&
			Robot::oi->getRightDriverStick()->GetTrigger() == true)
	{
		return true;
	}
	else
		return false;
}
// Called once after isFinished returns true
void TriggerCommand::End(){
	(new ShootAndCock())->Start();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TriggerCommand::Interrupted() {
	End();
}
