// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "UnloadShooter.h"
#define UNLOADING_SPEED 0.3
UnloadShooter::UnloadShooter() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void UnloadShooter::Initialize() {
	if(Robot::shooter->latchingLimitSwitch->Get() == false)
	{
		// TODO: Check the sign of the value being set
		Robot::shooter->loadingMotor->Set(UNLOADING_SPEED);
	}
}
// Called repeatedly when this Command is scheduled to run
void UnloadShooter::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool UnloadShooter::IsFinished() {
	return Robot::shooter->latchingLimitSwitch->Get();
}
// Called once after isFinished returns true
void UnloadShooter::End() {
	Robot::shooter->loadingMotor->Set(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UnloadShooter::Interrupted() {
	End();
}
